### ISSUE TITLE
Option to not output to canvas

### ISSUE THREAD

**Issue by jonaslund** [auduno/headtrackr#36]
Would be great to add the option of not having to render the face tracking to the canvas element, in case you only need the data from the events.

for example

``` js
htracker.init(videoInput, false);
```

**Comment by peepo** [comment]
Audun,

not sure of your level of interest**

As we move into the IoT this dependency on a browser, window, desktop and even OS may become a hindrance.

~related to W3C standards being maintained by browser developers.

I believe I already raised this with W3C some years ago.

If you know of any related action group, (nodejs ?)

please keep me in touch

Jonathan Chetwynd

'peepo'
