### ISSUE TITLE
facetrackingEvent not updating event.angle

### ISSUE THREAD

**Issue by ikbensiep** [auduno/headtrackr#42]
From the docs/reference it seems as `angle` should update when rotating my head, just as the `x` and `y` values do when I move. But no matter how I move, the `angle` is always at the same value:

![image](https://cloud.githubusercontent.com/assets/5741190/9377339/41d46be2-4718-11e5-966d-cc30e9fc1b09.png)

My code looks like this:
```
document.addEventListener('facetrackingEvent', 
	function (event) {
		console.info(event.angle);
	} 
);
```

Can anybody tell me wether this is correct behavior (and I'm misunderstanding something) or if this is a bug?

Thanks!

**Comment by auduno** [comment]
Hi, you might have to enable calculation of angles via the initialization parameter calcAngles, see the reference: 
http://auduno.github.io/headtrackr/documentation/reference.html
