### ISSUE TITLE
Head Tracking Demo No Longer Available

### ISSUE THREAD

**Issue by Francois-Laberge-Bose** [auduno/headtrackr#53]
hi,

Was hoping to reference your implementation of Facekat, using a different tracking method. The demo itself seems to be down:
http://www.shinydemos.com/facekat/

Any chance I could get at the source code or a link to a new url if it's just been moved.

Awesome work and good blog write up as well!
Francois

**Comment by auduno** [comment]
Yes, shinydemos.com is unfortunately down, and the facekat demo is not mirrored anywhere. The source code is available here though:

https://github.com/pwarocks/shinydemos/tree/master/demos/facekat

It hasn't been updated in a while, so I'm not sure how well it runs in modern browsers, but have a look!

**Comment by Francois-Laberge-Bose** [comment]
Awesome. Thanks!
